### ISSUE TITLE
Dynamic target collection path

### ISSUE THREAD

**Issue by michaelprichardson** [GitLiveApp/integrify#1]
Currently integrify only supports the path specified `db.collection(target.collection)` or `db.collectionGroup(target.collection)`. The only way to get around this is to use the `isCollectionGroup` flag. This requires  an index to be set up and could possibly cause issues if there are two collections of the same name but different type (less likely).

The idea would be to use the parameters from the source collection in the target collection
```
source: {
    collection: 'master/{someId}/detail',
  },
targets: [
    {
      collection: 'details/{someId}/more_detail',
      foreignKey: 'masterId',
    },
],
```

Being able to use a field from the source document might be possible too.

**Comment by nbransby** [comment]
I think perhaps we should change the syntax in the target to use a variable from the source path as if we keep the existing syntax people could easily unintentionally use the variable if they used the same name, just `{id}` for example.

I suggest we use $varName in the target path to consume a variable from the source path and throw an error if it does not exist

```
source: {
    collection: 'master/{someId}/detail',
  },
targets: [
    {
      collection: 'details/$someId/more_detail',
      foreignKey: 'masterId',
    },
],
```
